export const products = [
  {
    id: "plato-circular",
    name: "Plato circular",
    description: "Plato circular de cerámica artesanal, perfecto para servir aperitivos o como elemento decorativo.",
    price: 15,
    image: "/placeholder.svg?height=400&width=400",
    category: "platos",
    featured: true,
  },
  {
    id: "vaso-palo",
    name: "Vaso palo",
    description: "Vaso de cerámica con textura natural, ideal para bebidas calientes o frías.",
    price: 12,
    image: "/placeholder.svg?height=400&width=400",
    category: "vasos",
    featured: true,
  },
  {
    id: "plato-oval",
    name: "Plato oval",
    description: "Plato oval de cerámica con acabado artesanal, perfecto para servir platos principales.",
    price: 18,
    image: "/placeholder.svg?height=400&width=400",
    category: "platos",
  },
  {
    id: "plato-filo",
    name: "Plato filo",
    description: "Plato con borde fino y elegante, hecho a mano con cerámica de alta calidad.",
    price: 16,
    image: "/placeholder.svg?height=400&width=400",
    category: "platos",
  },
  {
    id: "florero-pequeno",
    name: "Florero pequeño",
    description: "Florero pequeño de cerámica, ideal para flores individuales o pequeños arreglos.",
    price: 22,
    image: "/placeholder.svg?height=400&width=400",
    category: "floreros",
    featured: true,
  },
  {
    id: "florero-mediano",
    name: "Florero mediano",
    description: "Florero de tamaño mediano con forma orgánica, perfecto para arreglos florales.",
    price: 28,
    image: "/placeholder.svg?height=400&width=400",
    category: "floreros",
  },
  {
    id: "taza-cafe",
    name: "Taza café",
    description: "Taza de café artesanal con acabado rústico, perfecta para disfrutar de tu bebida favorita.",
    price: 14,
    image: "/placeholder.svg?height=400&width=400",
    category: "vasos",
  },
  {
    id: "bowl-pequeno",
    name: "Bowl pequeño",
    description: "Bowl pequeño de cerámica, ideal para servir snacks, salsas o como elemento decorativo.",
    price: 16,
    image: "/placeholder.svg?height=400&width=400",
    category: "bowls",
    featured: true,
  },
]
